### ISSUE TITLE
FYI - Reddit Thread claim that SNAP broke Audacity

### ISSUE THREAD

**Issue by bmullan** [diddlesnaps/audacity#10]
Saw this thread on Reddit about someone claiming SNAP broke Audacity...

https://www.reddit.com/r/linuxquestions/comments/cpo729/im_told_snap_broke_audacity/

Wanted to make you aware of the thread as some responses are blaming SNAP which I don't know if valid or not.

Brian

**Comment by diddledan** [comment]
Thanks Brian :-)

**Comment by diddledan** [comment]
I'm going to close this issue. The problem the original user was encountering is a known limitation of strictly-confined Snap packages that is not likely to change any time soon.
