### ISSUE TITLE
Not installable

### ISSUE THREAD

**Issue by mook765** [diddlesnaps/audacity#13]
Can't install Audacity due to the missing plug `gtk-2-themes` which seems to be removed from the snap store.

**Comment by diddledan** [comment]
The plug you cite is provided by the snap called `gtk-common-themes`. This should be automatically installed when you install audacity. If it isn't then you likely have a bug in snapd. Please raise this issue with not automatically installing the relevant dependency snap on forum.snapcraft.io where the snapd developers can help.

**Comment by mook765** [comment]
According to the [yaml-file](https://github.com/diddlesnaps/audacity/blob/master/snap/snapcraft.yaml) the snap `gtk-2-themes` is needed, does the yaml-file needs to be updated?

    snap find gtk-2-themes
    Name             Version  Publisher  Notes  Summary
    adapta-gtk-snap  0.2      kd913      -      Adapta: An adaptive Gtk+ theme based on Material Design    Guidelines.

**Comment by mook765** [comment]
Trying to install the snap `audacity` again I cannot reproduce this anymore, it installed successfully.
