### ISSUE TITLE
Audacity 2.4.0 Released

### ISSUE THREAD

**Issue by pixelr0** [diddlesnaps/audacity#14]
Audacity 2.4.0 Released
 https://www.audacityteam.org/audacity-2-4-0-released/

**Comment by alexmurray** [comment]
FYI - upstream paused the rollout of 2.4.0 due to possible project corruption issues (from the link above)

> We’ve temporarily re-instated the 2.3.3 release for downloads whilst we investigate a serious bug that affects 2.4.0 on Windows Mac and Linux. The bug causes loss/corruption of audio.

> Currently we think the bug happens when you have two projects open at the same time and paste audio from one project into the other. Thanks to Jack L from FreeBSD for alerting us to the problem and giving us steps to reproduce it.

**Comment by diddledan** [comment]
2.4.1 is now in the store
