### ISSUE TITLE
GTK2 plugin

### ISSUE THREAD

**Issue by monochromec** [diddlesnaps/audacity#15]
Is there a reason why the snap is connected to GTK2 instead of GTK3? The look and feel on a modern Ubuntu is quite old-fashioned compared to the rest of a Gnome shell based system.

**Comment by diddledan** [comment]
The Snap Package uses GTK2 because that is what upstream Audacity recommend. I've experimented with GTK3 but it doesn't work well currently. When upstream moves to GTK3 I will update the Snap to follow along, but until then this is unlikely to be fixable.
