### ISSUE TITLE
Language and app-menu

### ISSUE THREAD

**Issue by Coeur-Noir** [diddlesnaps/audacity#16]
Hi,

Ubuntu Budgie 20.04 here.

Audacity snap 2.4.1.

⋅ app-menu is not send to global-menu-applet ( in top panel ),
⋅ only english language available,
⋅ light-grey background in some bars look out of place.

![audacity_snap](https://user-images.githubusercontent.com/1895947/83358171-fd07cc00-a371-11ea-98b0-e4f1f3d8687e.png)

Coming from there → https://discourse.ubuntubudgie.org/t/audacity-not-enough-height-for-some-tools/3703 → I was looking for better toolbox : 
![audacity](https://user-images.githubusercontent.com/1895947/83358261-9d5df080-a372-11ea-8cc5-b8a57e733f06.png)

**Comment by diddledan** [comment]
I've just pushed a new build. You should now have a fully localised interface, and the appmenu in Ubuntu Budgie should also work correctly. I'm not sure what I can do about the grey boxes that are looking rather ugly...

**Comment by Coeur-Noir** [comment]
I can confirm interface is now in my language, and the appmenu works correctly in Ubuntu Budgie.

Thank you !

Regarding ugly boxes, I guess that's how they are themed…
