### ISSUE TITLE
Audacity snap in stable channel is Alpha version

### ISSUE THREAD

**Issue by beardyjesse** [diddlesnaps/audacity#2]
There are multiple channels that snaps can be allocated to (stable, candidate, beta, edge) so that users can select their preference for new features vs stability.  All channels of the Audacity snap have the Alpha in, at the time of writing 2.3.0-alpha-Aug 10. When you load audacity it actually suggests that you change to using the stable version;

>The version of Audacity you are using is an Alpha test version. We strongly recommend that you use our latest stable released version, which has full documentation and support. 

Can the alpha version be put in the edge channel and stable in the stable channel?

>$ snap info audacity
**channels:                             
stable:    0+git.fa50578 (15) 103MB -
candidate: ↑                        
beta:      ↑                        
edge:      0+git.fa50578 (15) 103MB -
installed:   0+git.fa50578 (15) 103MB -**

**Comment by diddledan** [comment]
Thanks for the prod, Jesse :-)

The reason it's currently an alpha release is because it's building a fork which includes a TMPDIR patch. This patch has been accepted upstream now, so I can stop using the fork but the upstream stable release 2.2 doesn't include the patch.

**Comment by beardyjesse** [comment]
Hi, thanks for getting back to me.  Sorry if I'm a little slow, but is the alpha tag added because it's 2.3 + a fork?  Now that 2.3 includes the fork will it become 2.3 beta?
Also how come the snap isn't of the 2.2 stable version?  Is this TMPDIR needed for the snap?

**Comment by diddledan** [comment]
The fork was based off the 2.2.2 tag so I'm not sure why it is saying it's 2.3-alpha - apart from my patch the code _should_ be identical to the stable 2.2.2.

The TMPDIR patch is required for snap usage, yes. The app originally hardcoded a path in `/var/tmp` which is inaccessible when running in a confined snap, so I added the patch to support parsing the `TMPDIR` environment variable.

Upstream are gearing up for the 2.3.0 release soon so I'll be reverting to their repo at that point and building the specific tag.

**Comment by beardyjesse** [comment]
Thanks for the clarification.  I'm new to the Snap universe so appreciate you taking the time to respond and will follow this snap upgrade as a learning tool.  Have a good one.
