### ISSUE TITLE
Access to non-default ALSA? devices

### ISSUE THREAD

**Issue by whitty** [diddlesnaps/audacity#29]
Apologies if this is a duplicate of #28 - I didn't want to pile on with possibly unrelated information.

In 20.04 (apt) packaged Audacity we see a number of possible devices to select from:

![image](https://user-images.githubusercontent.com/194537/132294180-e49fb4d6-c19d-4ca5-90fa-384790b32b37.png)

in Snap packaged Audacity (857) we see only `default`:

![image](https://user-images.githubusercontent.com/194537/132294410-cee6f204-279d-4743-a615-af328d8f1c08.png)

 Is this expected behaviour?  Is this what other people are seeing.  Reading "#28" suggests that  `>857` is giving failure to list _any_ device, but maybe that is the same issue I am seeing, but in 857 itself?

I'm using the ? on ALSA in the topic, because the UI glitches in the apt Audacity mean that the "ALSA" dropdown brings up the device selection drop-down I don't know if there are actually more "audio frameworks" to choose from.  In snap ALSA is definitively all there is.

This may be a limit of snap confinement - or may be related to the failure being tracked in #28 - or maybe something misconfigured on my end.

Any suggestions appreciated.

Random extra info:

```
...
snap-id:      KTe2wdAu5JKdRDUgYBuXXGjDXyzobvFI
tracking:     latest/stable
refresh-date: 42 days ago, at 08:34 AEST
channels:
  latest/stable:    3.0.2 2021-07-26 (857) 196MB -
  latest/candidate: 3.0.2 2021-07-26 (907) 196MB -
  latest/beta:      ↑                            
  latest/edge:      3.0.2 2021-07-12 (910) 246MB -
installed:          3.0.2            (857) 196MB -
```

Running 20.04

I am in the `audio` group(s)

```
$ snap version
snap    2.51.4
snapd   2.51.4
series  16
ubuntu  20.04
kernel  5.11.0-25-generic
```

```
$ cat /sys/fs/cgroup/devices/snap.audacity.audacity/devices.list
cat: /sys/fs/cgroup/devices/snap.audacity.audacity/devices.list: No such file or directory
```

```
Interface               Plug                      Slot                              Notes
alsa                    audacity:alsa             -                                 -
audio-playback          audacity:audio-playback   :audio-playback                   -
audio-record            audacity:audio-record     -                                 -
content[gtk-2-engines]  audacity:gtk-2-engines    gtk2-common-themes:gtk-2-engines  -
content[gtk-2-themes]   audacity:gtk-2-themes     gtk-common-themes:gtk-2-themes    -
content[icon-themes]    audacity:icon-themes      gtk-common-themes:icon-themes     -
content[sound-themes]   audacity:sound-themes     gtk-common-themes:sound-themes    -
desktop                 audacity:desktop          :desktop                          -
desktop-legacy          audacity:desktop-legacy   :desktop-legacy                   -
gsettings               audacity:gsettings        :gsettings                        -
home                    audacity:home             :home                             -
jack1                   audacity:jack1            -                                 -
network                 audacity:network          :network                          -
network-bind            audacity:network-bind     :network-bind                     -
pulseaudio              audacity:pulseaudio       :pulseaudio                       -
removable-media         audacity:removable-media  -                                 -
unity7                  audacity:unity7           :unity7                           -
wayland                 audacity:wayland          :wayland                          -
x11                     audacity:x11              :x11                              -
```

**Comment by diddledani** [comment]
You can gain access to your alsa stack, if you trust the snap, by granting the `alsa` permission. By default, this is disabled due to the extra access it grants the snap to your system for security. To do this, run:

```bash
sudo snap connect audacity:alsa
```

Or find Audacity in the Snap Store GUI app and choose to manage its permissions followed by toggling the ALSA permission.

**Comment by whitty** [comment]
Thanks for the response - In reading #28 - I thought this was automagically applied in <= 857  - I hadn't seen the "manual" reference in the connections listing in #28.

Thanks
