### ISSUE TITLE
unable to load ffmpeg from the ffmpeg-snap

### ISSUE THREAD

**Issue by mattiaswerner** [diddlesnaps/audacity#3]
Under preferences-->libraries,

Audacity is unable to detect the ffmpeg library if it's only installed as a snap.

Unable to locate it manually as well as the app is restricted from looking in the snap directory.

**Comment by emptythevoid** [comment]
I'd also like to know how to work around this problem.  I frequently have to import audio from video (for noise reduction) and without the ffmpeg library, this stops working.

**Comment by emptythevoid** [comment]
It appears that the snap has libmp3 built in (/home/snap/audacity/<number>/usr/lib/x86_64-linux-gnu/libmp3lame.so.0.0.0).  Could the libavformat library also be put in there so Audacity can use it by default?

**Comment by diddledan** [comment]
ffmpeg will be in a new revision once the builders have built the package.
