### ISSUE TITLE
Plugin Directories Are Not Being Parsed Correctly

### ISSUE THREAD

**Issue by CreationTribe** [diddlesnaps/audacity#31]
So you know what I've looked at - I've made sure audacity's permissions were set correctly and I've removed and re-installed it several times to the same effect.

Some of the Nuqist plugins are not showing up - not even in the plugin manager.

I've downloaded the .ny for the built-in Limiter (as well as a few other limiters like limiter2 and both broadcast limiters II and III)
I placed them in `~/snap/audacity/current/.audacity-data/Plug-Ins/` still to no effect.

I've also renamed audacity.cfg, pluginregistery.cfg, and pluginsettings.cfg to force regeneration ... and still there are several built-in plugins that are not showing up in the plugin manager, not even under the disabled plugins.

The only plugins of any sort that are showing up are:

Amplify
Auto Duck
Bass and Treble
Change Pitch
Change Speed
Change Tempo
Chirp
Classic Filters
Click Removal
Compressor
Distortion
DTMF Tones
Echo
Fade In
Fade Out
Filter Curve EQ
Find Clipping
Graphic EQ
Invert
Loudness Normalization
Noise
Noise Reduction
Normalize
Paulstretch
Phaser
Repair
Repeat
Reverb
Reverse
Silence
Sliding Stretch
Stereo To Mono
Tone
Truncate Silence
Wahwah

... that's it. This just started after the last update on September 24th ...
I've done everything I could possibly think of to no effect.

And just to verify that the nyquist plugins do exist in the correct directory, I'll past the results of the plug-ins directory: `/snap/audacity/913/usr/share/audacity/plug-ins/`

-rw-r--r-- 1 root root  7971 Sep 24 06:40 adjustable-fade.ny
-rw-r--r-- 1 root root  1297 Sep 24 06:40 beat.ny
-rw-r--r-- 1 root root  4475 Sep 24 06:40 clipfix.ny
-rw-r--r-- 1 root root  5001 Sep 24 06:40 crossfadeclips.ny
-rw-r--r-- 1 root root  3095 Sep 24 06:40 crossfadetracks.ny
-rw-r--r-- 1 root root  4402 Sep 24 06:40 delay.ny
-rw-r--r-- 1 root root  5996 Sep 24 06:40 equalabel.ny
-rw-r--r-- 1 root root  5828 Sep 24 06:40 eq-xml-to-txt-converter.ny
-rw-r--r-- 1 root root  1529 Sep 24 06:40 highpass.ny
-rw-r--r-- 1 root root 10446 Sep 24 06:40 label-sounds.ny
-rw-r--r-- 1 root root  4697 Sep 24 06:40 limiter.ny
-rw-r--r-- 1 root root  1522 Sep 24 06:40 lowpass.ny
-rw-r--r-- 1 root root  6547 Sep 24 06:40 noisegate.ny
-rw-r--r-- 1 root root  1173 Sep 24 06:40 notch.ny
-rw-r--r-- 1 root root  8429 Sep 24 06:40 nyquist-plug-in-installer.ny
-rw-r--r-- 1 root root  1655 Sep 24 06:40 pluck.ny
-rw-r--r-- 1 root root  6843 Sep 24 06:40 rhythmtrack.ny
-rw-r--r-- 1 root root  2835 Sep 24 06:40 rissetdrum.ny
-rw-r--r-- 1 root root  2338 Sep 24 06:40 rms.ny
-rw-r--r-- 1 root root 17947 Sep 24 06:40 sample-data-export.ny
-rw-r--r-- 1 root root  3990 Sep 24 06:40 sample-data-import.ny
-rw-r--r-- 1 root root  4780 Sep 24 06:40 spectral-delete.ny
-rw-r--r-- 1 root root  2840 Sep 24 06:40 SpectralEditMulti.ny
-rw-r--r-- 1 root root  2844 Sep 24 06:40 SpectralEditParametricEQ.ny
-rw-r--r-- 1 root root  2752 Sep 24 06:40 SpectralEditShelves.ny
-rw-r--r-- 1 root root  1448 Sep 24 06:40 StudioFadeOut.ny
-rw-r--r-- 1 root root  1588 Sep 24 06:40 tremolo.ny
-rw-r--r-- 1 root root 12539 Sep 24 06:40 vocalrediso.ny
-rw-r--r-- 1 root root  5337 Sep 24 06:40 vocoder.ny

Anyway - thank you for supporting this project and keeping it up on the snap store :)
Let me know if you need anymore information.

**Comment by alexmurray** [comment]
Looking at the log in `Help -> Diagnostics -> Show Log` it shows:

```
15:30:16: Warning: Critical Nyquist files could not be found. Nyquist effects will not work.
```

(full log below)

```
15:30:16: Audacity 3.0.4-alpha-20210924
15:30:16: Warning: Critical Nyquist files could not be found. Nyquist effects will not work.
15:30:18: Trying to load FFmpeg libraries...
15:30:18: Trying to load FFmpeg libraries from system paths. File name is 'libavformat.so.58'.
15:30:18: Checking for monolithic avformat from 'libavformat.so.58'.
15:30:18: avformat not monolithic
15:30:18: Loading avutil from '/snap/audacity/913/usr/lib/x86_64-linux-gnu/libavutil.so.56.31.100'.
15:30:18: Loading avcodec from '/snap/audacity/913/usr/lib/x86_64-linux-gnu/libavcodec.so.58.54.100'.
15:30:18: Loading avformat from 'libavformat.so.58'.
15:30:18: Actual avutil path /snap/audacity/913/usr/lib/x86_64-linux-gnu/libavutil.so.56.31.100
15:30:18: Actual avcodec path /snap/audacity/913/usr/lib/x86_64-linux-gnu/libavcodec.so.58.54.100
15:30:18: Actual avformat path /snap/audacity/913/usr/lib/x86_64-linux-gnu/libavformat.so.58.29.100
15:30:18: Importing symbols...
15:30:18: All symbols loaded successfully. Initializing the library.
15:30:18: Retrieving FFmpeg library version numbers:
15:30:18:    AVCodec version 0x3a3664 - 58.54.100 (built against 0x3a3664 - 58.54.100)
15:30:18:    AVFormat version 0x3a1d64 - 58.29.100 (built against 0x3a1d64 - 58.29.100)
15:30:18:    AVUtil version 0x381f64 - 56.31.100 (built against 0x381f64 - 56.31.100)
15:30:18: FFmpeg libraries loaded successfully.
```

**Comment by CreationTribe** [comment]
Crazy, right? I haven't tried the apt-get or raw install ... but do you think this is an issue with the main code-base or something to do with snap permissions?

**Comment by diddledani** [comment]
I'm not sure what the problem is, just yet. thank you for raising this issue - I'll try to look into it later today

**Comment by diddledani** [comment]
I've found the problem. The builder is building a new package now, which will appear in the edge channel when complete.
