### ISSUE TITLE
audacity has not come in spanish

### ISSUE THREAD

**Issue by Lvaskz** [diddlesnaps/audacity#4]
HI, this release of audacity come not in spanish.  is there plans to translate it?

**Comment by Lvaskz** [comment]
any progress?

**Comment by diddledan** [comment]
Can you try build 211 (it is in stable as of a moment ago) to see if it fixes the language issue?

**Comment by Lvaskz** [comment]
Build? Sorry I am only a user, I have no idea how to do that

**Comment by diddledan** [comment]
in a terminal run `snap info audacity` to see what build you currently have. If it is not 211 or 212 then run `sudo snap refresh --stable audacity` to get the latest one.

**Comment by Lvaskz** [comment]
Ok I will thanks

**Comment by Lvaskz** [comment]
Nope, I installed 2.3.1 version It still in english, but many languages are loaded, except spanish

**Comment by Lvaskz** [comment]
Hi, I installed the deb package and It has the same issue. So I will close this because spanish translation is not an issue related to snap package

**Comment by diddledan** [comment]
Thanks for following up :-)
