### ISSUE TITLE
Menu bar of audacity do not appear in Ubuntu 16.04.6 in snap version of audacity.

### ISSUE THREAD

**Issue by aldrinpscastro** [diddlesnaps/audacity#8]
Hello. The menu bar do not appear in Ubuntu 16.04.6 in snap version of audacity. Only shows "Audacity". I cannot acess preferences or plugins.

**Comment by diddledan** [comment]
I've just pushed a new release that I think will fix the menu for you. Could you give it another try to see if it works better now?

**Comment by aldrinpscastro** [comment]
It's works now.
